//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.13 at 05:37:37 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/schemas/clinic/treatment", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package edu.stevens.cs.cs548.clinic.schema;
