//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 09:31:44 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/clinic/schemas/patient")
package edu.stevens.cs548.clinic.service.dto.patient;
